# Generated by Django 4.1.7 on 2023-03-28 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ball', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ball',
            options={'ordering': ['id'], 'verbose_name': 'Известные футболисты', 'verbose_name_plural': 'Известные футболисты'},
        ),
    ]
